"""Refresh the CDN/cloud scope feeds (§3.8b / §3.9).

Fetches published provider ranges (AWS ip-ranges.json, Cloudflare) and writes
``core/data/cloud_ranges.json``. Parsers are pure and tested; the fetch/write is
the ``__main__`` path. Keeping the feed fresh is what stops Vantari aggressively
scanning infrastructure a customer does not own.
"""

from __future__ import annotations

import json
from pathlib import Path

AWS_URL = "https://ip-ranges.amazonaws.com/ip-ranges.json"
CLOUDFLARE_URL = "https://www.cloudflare.com/ips-v4"

_DATA_FILE = Path(__file__).resolve().parents[1] / "core" / "data" / "cloud_ranges.json"


def parse_aws(payload: dict) -> dict[str, list[str]]:
    """Split AWS prefixes into CDN (CloudFront) vs generic cloud-shared ranges."""
    cdn: set[str] = set()
    shared: set[str] = set()
    for prefix in payload.get("prefixes", []):
        cidr = prefix.get("ip_prefix")
        if not cidr:
            continue
        if prefix.get("service") == "CLOUDFRONT":
            cdn.add(cidr)
        elif prefix.get("service") in ("EC2", "S3", "ELB", "GLOBALACCELERATOR"):
            shared.add(cidr)
    return {"cdn": sorted(cdn), "cloud_shared": sorted(shared)}


def parse_cloudflare(text: str) -> list[str]:
    return sorted({line.strip() for line in text.splitlines() if line.strip()})


def build_feed(*, aws: dict[str, list[str]], cloudflare: list[str]) -> dict:
    """Assemble the cloud_ranges.json structure from parsed feeds."""
    return {
        "_meta": {"description": "Auto-generated by scripts/update_scope_feeds.py"},
        "providers": [
            {"name": "cloudflare", "class": "cdn", "cidrs": cloudflare},
            {"name": "aws_cloudfront", "class": "cdn", "cidrs": aws.get("cdn", [])},
            {"name": "aws_cloud", "class": "cloud_shared", "cidrs": aws.get("cloud_shared", [])},
        ],
    }


async def main() -> None:  # pragma: no cover - real network + file write
    import aiohttp

    async with aiohttp.ClientSession() as session:
        async with session.get(AWS_URL) as r:
            aws = parse_aws(await r.json(content_type=None))
        async with session.get(CLOUDFLARE_URL) as r:
            cloudflare = parse_cloudflare(await r.text())

    feed = build_feed(aws=aws, cloudflare=cloudflare)
    _DATA_FILE.write_text(json.dumps(feed, indent=2))
    total = sum(len(p["cidrs"]) for p in feed["providers"])
    print(f"wrote {total} ranges to {_DATA_FILE}")


if __name__ == "__main__":  # pragma: no cover
    import asyncio

    asyncio.run(main())
