"""Refresh the CDN/cloud scope feeds (§3.8b / §3.9, §7 Phase G auto-update job).

Fetches published provider ranges (AWS ip-ranges.json, Cloudflare) and updates
``core/data/cloud_ranges.json``. Parsers are pure and tested; the fetch/write is
the ``__main__`` path.

**This file is a safety control, not a cache.** The engine classifies an IP as
CDN/CLOUD_SHARED from these ranges, and those classes are what restrict Vantari to
HTTP-layer probing (§3.9). A range that falls out of the feed stops being
recognised as shared infrastructure — so a *bad update is not a stale feed, it is
a removed protection*. Everything below is shaped by that asymmetry: adding ranges
is cheap and safe, losing them is not.

Two rules follow, and both were violated by the original version:

**Merge, never clobber.** This script only fetches Cloudflare and AWS. It used to
rewrite the whole file from what it fetched, which silently deleted the akamai,
fastly, google_cloud_lb and azure_front_door providers — four CDNs downgraded from
"HTTP-layer only" to unclassified, by the daily cron the deploy guide recommends.
It now replaces only the providers it actually owns.

**Sanity-check before writing.** An error page parsed as JSON, or a partial fetch,
yields an empty range list. Writing that removes protection just as effectively as
deleting the provider. A shrinking feed is refused.
"""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path

AWS_URL = "https://ip-ranges.amazonaws.com/ip-ranges.json"
CLOUDFLARE_URL = "https://www.cloudflare.com/ips-v4"

_DATA_FILE = Path(__file__).resolve().parents[1] / "core" / "data" / "cloud_ranges.json"

#: Providers this script fetches and is therefore allowed to replace. Anything else
#: in the file is maintained elsewhere and must survive an update untouched.
MANAGED_PROVIDERS = ("cloudflare", "aws_cloudfront", "aws_cloud")

#: A managed provider may not lose more than this fraction of its ranges in one
#: update. Real feeds grow or wobble by a few percent; a 30% drop means the fetch
#: was wrong, not that AWS gave back a quarter of the internet.
MAX_SHRINK = 0.3


class FeedRejected(RuntimeError):
    """The fetched feed looked wrong. The existing file is left alone."""


def parse_aws(payload: dict) -> dict[str, list[str]]:
    """Split AWS prefixes into CDN (CloudFront) vs generic cloud-shared ranges."""
    cdn: set[str] = set()
    shared: set[str] = set()
    for prefix in payload.get("prefixes", []):
        cidr = prefix.get("ip_prefix")
        if not cidr:
            continue
        if prefix.get("service") == "CLOUDFRONT":
            cdn.add(cidr)
        elif prefix.get("service") in ("EC2", "S3", "ELB", "GLOBALACCELERATOR"):
            shared.add(cidr)
    return {"cdn": sorted(cdn), "cloud_shared": sorted(shared)}


def parse_cloudflare(text: str) -> list[str]:
    return sorted({line.strip() for line in text.splitlines() if line.strip()})


def build_feed(*, aws: dict[str, list[str]], cloudflare: list[str], current: dict | None = None):
    """Merge freshly-fetched ranges into *current*, preserving unmanaged providers.

    Only :data:`MANAGED_PROVIDERS` are replaced. Providers this script does not
    fetch (akamai, fastly, google_cloud_lb, azure_front_door) are carried through
    verbatim — deleting them would quietly convert four CDNs into unclassified
    address space that the engine no longer restricts to HTTP-layer probing.
    """
    fetched = [
        {"name": "cloudflare", "class": "cdn", "cidrs": cloudflare},
        {"name": "aws_cloudfront", "class": "cdn", "cidrs": aws.get("cdn", [])},
        {"name": "aws_cloud", "class": "cloud_shared", "cidrs": aws.get("cloud_shared", [])},
    ]
    kept = [
        p for p in (current or {}).get("providers", []) if p.get("name") not in MANAGED_PROVIDERS
    ]
    return {
        "_meta": {
            "description": (
                "Managed providers auto-generated by scripts/update_scope_feeds.py; "
                "others are hand-maintained and preserved across updates."
            ),
            "managed": list(MANAGED_PROVIDERS),
        },
        "providers": kept + fetched,
    }


def _counts(feed: dict) -> dict[str, int]:
    return {p["name"]: len(p.get("cidrs", [])) for p in feed.get("providers", [])}


def validate_feed(new: dict, current: dict | None) -> None:
    """Refuse an update that would remove protection. Raises :class:`FeedRejected`.

    Failing here leaves the previous feed in place, which is the safe direction: a
    slightly stale range list still classifies known shared infrastructure, whereas
    an empty one classifies nothing and lets it look like ordinary public address
    space.
    """
    new_counts = _counts(new)
    for name in MANAGED_PROVIDERS:
        if new_counts.get(name, 0) == 0:
            raise FeedRejected(f"{name} came back with zero ranges — refusing to write")

    old_counts = _counts(current or {})
    for name, before in old_counts.items():
        after = new_counts.get(name)
        if after is None:
            raise FeedRejected(f"{name} would disappear from the feed — refusing to write")
        if before and after < before * (1 - MAX_SHRINK):
            raise FeedRejected(
                f"{name} shrank {before} → {after} ranges (>{MAX_SHRINK:.0%}) — refusing to write"
            )


def write_feed(feed: dict, path: Path) -> None:
    """Write atomically: a partial write leaves unparseable JSON, and the engine
    loads this at startup — a truncated feed is a worker that will not boot."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as fh:
            json.dump(feed, fh, indent=2)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp, path)  # atomic on POSIX
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise


def load_current(path: Path) -> dict | None:
    try:
        return json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return None


async def update_scope_feeds(path: Path | None = None, *, fetch=None) -> dict:
    """Fetch → merge → validate → write. Returns the feed that was written.

    ``fetch`` is injectable so this is testable without network (house style).
    """
    from core.logging import logger

    path = path or _DATA_FILE
    aws_payload, cloudflare_text = await (fetch or _default_fetch)()
    current = load_current(path)
    feed = build_feed(
        aws=parse_aws(aws_payload), cloudflare=parse_cloudflare(cloudflare_text), current=current
    )
    validate_feed(feed, current)
    write_feed(feed, path)
    total = sum(len(p["cidrs"]) for p in feed["providers"])
    logger.info("scope feeds updated: {} ranges across {} providers", total, len(feed["providers"]))
    return feed


async def _default_fetch():  # pragma: no cover - real network
    import aiohttp

    async with aiohttp.ClientSession() as session:
        async with session.get(AWS_URL) as r:
            aws = await r.json(content_type=None)
        async with session.get(CLOUDFLARE_URL) as r:
            cloudflare = await r.text()
    return aws, cloudflare


async def main() -> None:  # pragma: no cover - real network + file write
    feed = await update_scope_feeds()
    print(f"wrote {sum(len(p['cidrs']) for p in feed['providers'])} ranges to {_DATA_FILE}")


if __name__ == "__main__":  # pragma: no cover
    import asyncio

    asyncio.run(main())
